### PR TITLE
Updating 3.4.x

### PR DESCRIPTION
**Pull request by archaeogeek**

### CODE REVIEW

**Review by nmtoken — COMMENTED** [review]
request=getcapabailities is incorrect.  OGC standard (OWS common) tells us it must be case sensitive request=GetCapabilities

**Comment by archaeogeek** [comment]
@nmtoken thanks for the catch- indeed it's in src/main/plugin/iso19139.gemini22/convert/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilitiesLayer-to-19139.xsl. Please create an issue for this (and anything else you find)

**Comment by nmtoken** [comment]
@archaeogeek I'm not sure where I should raise the issue.  I thought a comment on the commit would be sufficient.  Are you saying I should raise a general/global issue to check that all GetCapabilities requests follow the OGC specification spelling

**Comment by archaeogeek** [comment]
@nmtoken comments tend to get lost, as they are not particularly visible in the main repository interface, and it's also hard to track their status. You can convert a comment into an issue by using the ... icon next to the smiley face. As to how generic/global it should be- in this case I'd refer to the specific commit that you've seen with the issue in it.

**Pull request merged**
